# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: capc-

# Set namespace for all resources
namespace: capc-system

# Labels to add to all resources and selectors.
labels:
- pairs:
    cluster.x-k8s.io/provider: "infrastructure-cloudstack"

resources:
  - ../../config/manager
patches:
- target:
    kind: Deployment
    name: controller-manager
    namespace: system
  path: manager_controller_patch.yaml
- target:
    kind: Deployment
    name: controller-manager
  patch: |-
    - op: remove
      path: /spec/template/spec/serviceAccountName

