namespace: capi-webhook-system

namePrefix: capc-

resources:
- ../../config/crd
- ../../config/manager
- ../../config/webhook
- ../../config/certmanager

configurations:
- ../../config/default/kustomizeconfig.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    cluster.x-k8s.io/provider: infrastructure-cloudstack
patches:
- path: patch_service_account.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    namespace: system
    version: v1
- path: ../../config/default/manager_image_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    version: v1
- path: ../../config/default/manager_webhook_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    version: v1
- path: ../../config/default/webhookcainjection_patch.yaml

vars:
- name: CERTIFICATE_NAMESPACE
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1
    name: serving-cert
  fieldref:
    fieldpath: metadata.namespace
- name: CERTIFICATE_NAME
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1
    name: serving-cert
  fieldref:
    fieldpath: metadata.name
- name: SERVICE_NAMESPACE
  objref:
    kind: Service
    version: v1
    name: webhook-service
  fieldref:
    fieldpath: metadata.namespace
- name: SERVICE_NAME
  objref:
    kind: Service
    version: v1
    name: webhook-service




