# Adds namespace to all resources.
namespace: capi-webhook-system

# Labels to add to all resources and selectors.
labels:
- pairs:
    cluster.x-k8s.io/provider: "infrastructure-cloudstack"

namePrefix: capc-

resources:
  - ../../config/crd
  - ../../config/manager
  - ../../config/webhook
  - ../../config/certmanager

# the following config is for teaching kustomize how to do var substitution
vars:
- name: CERTIFICATE_NAMESPACE
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1
    name: serving-cert
  fieldref:
    fieldpath: metadata.namespace
- name: CERTIFICATE_NAME
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1
    name: serving-cert
  fieldref:
    fieldpath: metadata.name
- name: SERVICE_NAMESPACE # namespace of the service
  objref:
    kind: Service
    version: v1
    name: webhook-service
  fieldref:
    fieldpath: metadata.namespace
- name: SERVICE_NAME
  objref:
    kind: Service
    version: v1
    name: webhook-service

configurations:
  - kustomizeconfig.yaml
patches:
- path: manager_webhook_patch.yaml
- path: webhook_ca_injection_patch.yaml
- target:
    kind: Deployment
    name: controller-manager
  patch: |-
    - op: remove
      path: /spec/template/spec/serviceAccountName



